### ISSUE TITLE
NumberFormatException: Invalid long: "null"

### ISSUE THREAD

**Issue by fi3te** [kekru/ILIASDownloader2#2]
at java.lang.Long.parseLong
at de.whiledo.iliasdownloader2.service.ILIASSoapService.getUserId

**Comment by John-By** [comment]
After entering all neccessary login data the program tries to sync with the server but breaks throwing the following error message before anything was found:

java.lang.NumberFormatException: null
at java.base/java.lang.Long.parseLong(Long.java:670)
at java.base/java.lang.Long.parseLong(Long.java:832)
at de.adesso.iliasdownloader2.service.ILIASSoapService.getUserId(ILIASSoapService.java:334)
at de.adesso.iliasdownloader2.service.ILIASSoapService.getCourseIds(ILIASSoapService.java:338)
at de.adesso.iliasdownloader2.syncrunner.service.SyncService$3.run(SyncService.java:128)
at java.base/java.lang.Thread.run(Thread.java:832)
