### ISSUE TITLE
java.lang.NumberFormatException: null

### ISSUE THREAD

**Issue by JD00h** [kekru/ILIASDownloader2#7]
After entering all neccessary login and server data as described, the program tries to sync with the Konstanz University Ilias server (Ilias v5.4.17 2020-09-04), but breaks throwing the following error message:

java.lang.NumberFormatException: null
at java.base/java.lang.Long.parseLong(Long.java:670)
at java.base/java.lang.Long.parseLong(Long.java:832)
at de.adesso.iliasdownloader2.service.ILIASSoapService.getUserId(ILIASSoapService.java:334)
at de.adesso.iliasdownloader2.service.ILIASSoapService.getCourseIds(ILIASSoapService.java:338)
at de.adesso.iliasdownloader2.syncrunner.service.SyncService$3.run(SyncService.java:128)
at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by kekru** [comment]
Hi, unfortunately I can not debug it, because I don't have credentials für Uni Konstanz and I get  

```
de.whiledo.iliasdownloader2.exception.IliasAuthenticationException: Authentication failed: err_wrong_login
	at de.whiledo.iliasdownloader2.service.ILIASSoapService.login(ILIASSoapService.java:115)
	at de.whiledo.iliasdownloader2.syncrunner.service.SyncService.login(SyncService.java:173)
	at de.whiledo.iliasdownloader2.syncrunner.service.SyncService.startOrStopSync(SyncService.java:116)
	at de.whiledo.iliasdownloader2.swing.service.MainController.buttonClickedSynchronize(MainController.java:271)
	at de.whiledo.iliasdownloader2.swing.service.MainFrame$2.actionPerformed(MainFrame.java:101)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        ....
```

I just added a downloadlink for the newest version in README.md: [Download from JitPack](https://jitpack.io/com/github/kekru/ILIASDownloader2/ILIASDownloader-SwingFrontend/master-SNAPSHOT/ILIASDownloader-SwingFrontend-master-SNAPSHOT.jar).  
Maybe this could help, but I don't really think so.  
I think ILIAS changed something in der APIs and I didn't update this project for a long time.

**Comment by JL4J** [comment]
I study at the TH OWL and the program worked until about two weeks ago. The login still worked but I would get sililar errors when trying to download files. I have no idea if your issue is related to mine, but I did some investigation.

It turns out Ilias was updated, which changed how some endpoints of the SOAP API behave. The ```getFileXML``` endpoint now returns something like this:
```XML
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE File PUBLIC "-//ILIAS//DTD FileAdministration//EN" "https://www.th-owl.de/ecampus/xml/">
<!--Exercise Object-->
<File obj_id="object_id" version="1" max_version="1" size="1468" type="application/octet-stream" action="">
    <Filename>file_name</Filename>
    <Title>title</Title>
    <Description/>
    <Rating>0</Rating>
    <Versions>
        <Version version="1" max_version="1" date="1436206328" usr_id="user_id" action="create" rollback_version="" rollback_user_id="" mode="PLAIN">
           file in base64 encoding
        </Version>
    </Versions>
</File>
```

By changing XmlVersion.java the issue could be fixed easily for me, but this breaks the program for other unis since every uni seems to use a different Ilias version. This probably means somehow detecting the Ilias version and using the API accordingly. But with lack of public documentation this is more or less a reverse engineering effort. @kekru I would be down to help if such a project is started.

**Comment by kekru** [comment]
Hi @JL4J,
thanks for analysing!  
I think it would be possible to detect the Ilias version from the HTML of the login page or something like that.

But I don't have time to invest much effort in this project anymore.  
I also finished studying a few years ago and did not use the ILIAS Downloader since then

But if you want to contribute, Pull Requests are welcome :) 

Maybe I could help to set up some different versions of Ilias in docker, so we could test different versions of Ilias server
